export default {
  name: 'VS Forms',
  company: 'Voyager Social AI',
  brandingText: 'VS Forms by Voyager Social AI',
  defaultTheme: 'vs-forms',
  supportEmail: 'support@voyagersocial.ai',
  app_name: "VS Forms",
  locale: "en",
  locales: { en: "EN" },
  githubAuth: null,
  notion: { worker: "https://notion-forms-worker.notionforms.workers.dev/v1" },
  links: {
    help_url: "https://help.voyagersocial.ai",
    github_url: "https://github.com/JhumanJ/OpnForm",
    github_forum_url: "https://github.com/JhumanJ/OpnForm/discussions",
    discord: "https://discord.gg/YTSjU2a9TS",
    twitter: "https://twitter.com/VoyagerSocialAI",
    zapier_integration:
      "https://zapier.com/developer/public-invite/146950/58db583730cc46b821614468d94c35de/",
    book_onboarding: "https://zcal.co/i/YQVGEULQ",
    feature_requests: "https://feedback.voyagersocial.ai/",
    changelog_url: "https://feedback.voyagersocial.ai/changelog",
    roadmap: "https://feedback.voyagersocial.ai/roadmap",
    tech_docs: "https://docs.voyagersocial.ai",
  },
}
