---
services:
  api: &api
    image: jhumanj/opnform-api:latest
    environment: &api-environment  # Add this anchor
      DB_HOST: ${DB_HOST:-forge}
      REDIS_HOST: redis
      DB_DATABASE: ${DB_DATABASE:-forge}
      DB_USERNAME: ${DB_USERNAME:-forge}
      DB_PASSWORD: ${DB_PASSWORD:-forge}
      DB_CONNECTION: ${DB_CONNECTION:-pgsql}
      FILESYSTEM_DISK: s3
      LOCAL_FILESYSTEM_VISIBILITY: public
    env_file:
    - ./api/.env
    volumes:
    - opnform_storage:/usr/share/nginx/html/storage:rw

  api-worker:
    image: jhumanj/opnform-api:latest
    command: php artisan queue:work
    environment:
      <<: *api-environment
      IS_API_WORKER: "true"
    env_file:
    - ./api/.env
    volumes:
    - opnform_storage:/usr/share/nginx/html/storage:rw

  ui:
    image: jhumanj/opnform-client:latest
    env_file:
    - ./client/.env

  ingress:
    image: nginx:1
    volumes:
      - ./docker/nginx.conf:/etc/nginx/templates/default.conf.template
    ports:
      - 80:80

volumes:
  postgres-data:
  opnform_storage:
